
## read in the clipped to bird point laz files generated by read_clip_write_laz_files.R
# then 'normalize' them: subtract the hydro-flattened digital elevation(terrain) map that was generated by the SVM folks.
# the output for each point saved to generated_data/norm_laz/ shows the height of each LiDAR return above ground level

#

# library(plyr)
library(lidR)
library(tidyverse)
library(sp)
library(rgdal)
library(sf)
library(rgeos)
library(raster)
# ------------------

# requires running all of CountPoints_get_point_coords.R

catalog_options(by_file = TRUE)
mayac.catalog <- catalog("generated_data/clipped_laz")


# these DTM rasters are already in the same State Plane projection as the laz files, so no need to reproject

# the clipped laz files have their CRS = NA

mayac_hydroDTM <- raster("generated_data/mayac_hydroDTM.tif")


read_norm <- function(zpoint){
  #zpoint <- "2L"
  #  zras <- sausal_hydroDTM
  
  zpath <- paste("generated_data/clipped_laz/clipped2_", zpoint, ".laz", sep = "")
  new_clipped2 <- readLAS(zpath)
  normalized <- lasnormalize(new_clipped2, mayac_hydroDTM, copy = TRUE)
  output_name <- paste("generated_data/norm_laz/norm_", zpoint, ".laz", sep = "")
  
  writeLAS(normalized, output_name)
  #return(normalized)
}

read_norm("1R")
read_norm("2L")
read_norm("3L") 
read_norm("4L") 
read_norm("5R") 
read_norm("6L")
read_norm("7L") 
read_norm("8L") 
read_norm("9R")
read_norm("10R") 
read_norm("11R") 
read_norm("12L") 
read_norm("13L") 
read_norm("14R") 
read_norm("15R") 
read_norm("16R")

read_norm("HOME2") 
read_norm("HOME3") 
read_norm("MCDO10") 
read_norm("MCDO6") 
read_norm("WERA1") 
read_norm("WERA2") 
read_norm("HOME5") 
read_norm("MCDO2") 
read_norm("MCDO11") 
read_norm("FORK10") 
read_norm("MCDO12") 
read_norm("LIIN2")
read_norm("LIIN3") 
read_norm("MIRA11") 
read_norm("MIRA12") 
read_norm("MIRA2") 
read_norm("BIHI2") 
read_norm("LIIN1") 
read_norm("LIIN4") 
read_norm("WERA3") 
read_norm("WEBL1") 
read_norm("WEBL3") 
read_norm("BIHI1") 
read_norm("BIHI3") 
read_norm("BIHI5") 
read_norm("BIHI6") 
read_norm("MIRA10") 
read_norm("BIHI4") 
read_norm("EABL2") 
read_norm("EARA1") 
read_norm("BEAR1") 
read_norm("EARA2")
read_norm("EARA3") 
read_norm("HIVA1") 
read_norm("HIVA3") 
read_norm("HIVA2")


# -----------------------------------------------
# generate all these function calls
birds.points.coords <- arrange(birds.points.coords, point)

for(i in 1:length(birds.points.coords$point)) {
  call_list <- paste("read_norm(", "\"", birds.points.coords$point, "\")", sep = "")
}
for(i in 1:length(call_list)){
  cat(call_list)
}

# -----------------------------------------------

